### ISSUE TITLE
捆绑瓦片

### ISSUE THREAD

**Issue by wgf120513** [PrincessGod/objTo3d-tiles#10]
你好，我想问下你说的捆绑多个瓦片到一个json文件里。
我是先把每个obj模型都转换成b3dm格式的模型，然后再转换，
还是说每个模型都生成一个瓦片，然后在捆绑到一个json文件中？

**Comment by PrincessGod** [comment]
@wgf120513 
不好意思，是我没有说明清楚。

需要先生成多个瓦片而不是`.b3dm`或`.i3dm`，然后再将多个瓦片进行捆绑。

因为每个瓦片有不同的瓦片信息，比如经纬度。

**Comment by wgf120513** [comment]
好的，感谢。我试一下。
