### ISSUE TITLE
Usage as a library

### ISSUE THREAD

**Issue by IgorGrechka** [PrincessGod/objTo3d-tiles#12]
Hi and thanks for the great job! Do you have an example of usage obj23dtiles as a library (run from JavaScript)? Thank you in advance!

**Comment by PrincessGod** [comment]
@IgorGrechka 

Are you mean [this](https://github.com/PrincessGod/objTo3d-tiles/blob/master/NODEUSAGE.md)?

**Comment by IgorGrechka** [comment]
@PrincessGod 

Oh! It was there! Thank you very much!
