### ISSUE TITLE
生成的3dtiles模型 部分结构丢失

### ISSUE THREAD

**Issue by eleven7** [PrincessGod/objTo3d-tiles#25]
###  生成的3dtiles文件 部分结构丢失

原obj格式的模型 通过window10  自带的3d builder 打开
![17v4xir rmk8ie t924](https://user-images.githubusercontent.com/20694705/43636205-fa1bb830-9743-11e8-9a87-5b47fc878ba1.png)

转化后的模型显示 部分结构丢失
![h3z h5dbp8 zfw prm 4](https://user-images.githubusercontent.com/20694705/43636374-79c1d0b0-9744-11e8-92d9-682d02e070f3.png)

后obj格式将其转化为gltf 格式的模式 部分结构也丢失且 丢失位置与3dtiles格式文件的位置相同同   通过window10 自带的3d builder 打开
![fz7 z 3 e l3d 0_s2bsdg9](https://user-images.githubusercontent.com/20694705/43636533-ebafba0c-9744-11e8-8c56-326cfec0fde1.png)

这是原文件
[test.zip](https://github.com/PrincessGod/objTo3d-tiles/files/2261100/test.zip)

**Comment by PrincessGod** [comment]
@eleven7 错误信息非常相信，可以使用 obj2gltf 转换后查看是否还是丢失，如果是可能需要你修改模型。

**Comment by eleven7** [comment]
通过cesiumlab转化则没有丢失
