### ISSUE TITLE
3d tile 模型分片位置重叠在一起

### ISSUE THREAD

**Issue by riematrix** [PrincessGod/objTo3d-tiles#28]
原始数据是分片的obj文件 使用如下命令全部转成tileset
obj23dtiles -i ??.obj --tileset

然后使用 
obj23dtiles combine -i .
合并tileset.json

客户端使用cesium加载tileset
    var viewer = new Cesium.Viewer('cesiumContainer');

    var tileset = viewer.scene.primitives.add(new Cesium.Cesium3DTileset({
        url : '../../SampleData/Cesium3DTiles/Tilesets/szylset/tileset.json'
    }));

    viewer.zoomTo(tileset, new Cesium.HeadingPitchRange(0, -0.5, 0));

结果在某个方向上tile重叠在一起

![image](https://user-images.githubusercontent.com/1978248/44851317-7866b600-ac92-11e8-84f9-0958516c263e.png)

数据文件
[szylset.zip](https://github.com/PrincessGod/objTo3d-tiles/files/2336112/szylset.zip)

**Comment by whalelu** [comment]
我也遇到了同样的问题，想问一下解决了吗？ @riematrix

**Comment by riematrix** [comment]
@whalelu 这是坐标系的问题 因为数据是y轴朝上 但cesium需要z轴朝上 这样才能贴地 我们是通过对原始数据做一次坐标转换解决的 具体转换方式您可以自己推导一下

**Comment by whalelu** [comment]
@riematrix 十分感谢！

**Comment by whalelu** [comment]
@riematrix 可以留个联系方式吗，我研究了一下还是不太明白

**Comment by riematrix** [comment]
发我主页的邮箱吧@whalelu

**Comment by whalelu** [comment]
@riematrix 你的主页似乎没有公开邮箱

**Comment by riematrix** [comment]
@whalelu 抱歉 发这个邮箱吧 Stanley.j.zhou@gmail.com
