### ISSUE TITLE
3d tiles in  wrong postion

### ISSUE THREAD

**Issue by neson6xd** [PrincessGod/objTo3d-tiles#44]
I use this tool to convert a obj to a single tileset, then, I show this model in cesium and it is in Sudan but the right place is China。Can someone help me?  The following is customTilesetOptions.json and tileset.json
**customTilesetOptions.json** 
`{
    "longitude": 119.95948074950003,
    "latitude": 31.68082139900001,
	"transHeight":  0.0,         
    "region":    true,        
    "box":      false,  
    "sphere":   false
}`

**tileset.json**
`{
  "asset": {
    "version": "0.0",
    "tilesetVersion": "1.0.0-obj23dtiles",
    "gltfUpAxis": "Y"
  },
  "geometricError": 200,
  "root": {
    "transform": [
      -0.5471536466732279,
      0.8370321899020303,
      0,
      0,
      -0.21914155605896873,
      -0.143249092426594,
      0.9651200318753161,
      0,
      0.8078365337989131,
      0.5280689449179611,
      0.2618077998704183,
      0,
      5153674.616673024,
      3368869.07612232,
      1659048.1064715665,
      1
    ],
    "boundingVolume": {
      "region": [
        119.95936855744625,
        31.680633143240144,
        119.95958835404977,
        31.681313337668144,
        -3,
        30
      ]
    },
    "geometricError": 0,
    "refine": "ADD",
    "content": {
      "url": "kjc.b3dm"
    }
  }
}
`

**Comment by Abelon38** [comment]
Hi!

I have built an aplication that uses this plugging and Cesium in order to
get the right position of your .obj. it will be on GitHub soon.

Regards
Abel

Den tis 23 nov. 2021 21:45luxiaodao123 ***@***.***> skrev:

**Comment by neson6xd** [comment]
Hi @Abelon38 

Thank you for your reply. I've found my problem that longitude and latitude must to be radian but I used degree in customTilesetOptions.json. After change that, the model is located in the right place.

**Comment by Abelon38** [comment]
Perfect!

But you have to add position manually?

Regards,  Abel

Den ons 1 dec. 2021 07:42luxiaodao123 ***@***.***> skrev:
